### ISSUE TITLE
I can add a tool with a purchase date in the future

### ISSUE THREAD

**Issue by ekraihan** [Renascentinc/retina-app#110]
If I select a date in the future and click the add button immediately after, the invalid date "slips through." See video below.

![future_purchase](https://cloud.githubusercontent.com/assets/17623856/26381430/be7b8c96-3ff2-11e7-8d92-43913eabc766.gif)

**Comment by Jbcampbe** [comment]
@ekraihan this is now addressed in #Josiahc.#82-fix-datepicker
