### ISSUE TITLE
I can put an underscore in the serial and model number fields

### ISSUE THREAD

**Issue by ekraihan** [Renascentinc/retina-app#118]

**Comment by amenders** [comment]
Also need to enforce database rules, i.e. max char count

**Comment by Jbcampbe** [comment]
@amenders I am going to make that one its own ticket.

**Comment by Jbcampbe** [comment]
@ekraihan @amenders this appears to be an issue with jquery validator. we rely on it to enforce alphanumeric. what do you think of pushing this ticket off to release_2.2.0 (I believe it may already be fixed in develop)

**Comment by Jbcampbe** [comment]
The problem is that in develop I am using a totally different way of validating... not jquery validator... : /
