### ISSUE TITLE
Tool can't be added when you open and close the purchaseDate field without selecting anything

### ISSUE THREAD

**Issue by ekraihan** [Renascentinc/retina-app#123]
Sometimes I can't submit a tool if the price is too long (i think?) The console throws an ember error:

![image](https://cloud.githubusercontent.com/assets/17623856/26536441/dc2b472a-4404-11e7-8f33-4398f8b3a2d0.png)

This may be an API issue. I'll be looking into it more.

**Comment by ekraihan** [comment]
I have this set for 2.2.0, but please, if it seems important for 2.1.0, move it :)

**Comment by Jbcampbe** [comment]
If that is the case then that issue should be fixed by #121 (when I get the correct char counts from jere)

**Comment by Jbcampbe** [comment]
@ekraihan is this solved by #122 ?

**Comment by ekraihan** [comment]
@josiah no, it isn't

**Comment by Jbcampbe** [comment]
Created a verifiable reproduce. When you open purchase date calendar and then close it without selecting a date then the `purchaseDate` property is set to `null` instead of empty string
