### ISSUE TITLE
{{URGENT}} Serial number search is case-sensitive

### ISSUE THREAD

**Issue by amenders** [Renascentinc/retina-app#133]
The search bar for serial numbers is case sensitive, meaning that a search with lowercase characters will return no results. @Jbcampbe this can be done as a hotfix.

**Comment by Jbcampbe** [comment]
@amenders would this be a backend issue? I can standardize the case when I send it to the backend but I think it is ultimately up to Jere and Chip wether or not this is case sensitive

**Comment by amenders** [comment]
All of the numbers are stored in the DB as uppercase. As the front end guys, we're sending the DB lowercase letters if that's what the user provides. We should package them into uppercase before sending, or ask that the API does so, or even in a stored proc. SOMEONE needs to convert the user entry to upper. :)

Amos Endersen
(317) 600-9236

**Comment by amenders** [comment]
Assigning to @ekraihan since this is an issue we want to resolve in the API

**Comment by ekraihan** [comment]
@Jbcampbe did you fix this? It seems to be fixed on the release branch....

**Comment by ekraihan** [comment]
@Jbcampbe even if you fixed this, please don't close it. I want to also add .toUppercase in the API

**Comment by Jbcampbe** [comment]
Hmm. No I haven't made any changes to it that I know off

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by amenders** [comment]
@jbcampbe, I would PERSONALLY like the fix to be on the API from a design patterns perspective.

Amos Endersen
(317) 600-9236

**Comment by Jbcampbe** [comment]
@ekraihan what is the current status on this?

**Comment by ekraihan** [comment]
@Jbcampbe all fixed. Closing
