### ISSUE TITLE
Make cart use the Ember Way to list tools

### ISSUE THREAD

**Issue by ekraihan** [Renascentinc/retina-app#146]
Currently, the items in the cart are delimited by ```<br>```.
Its seems like they should be listed using an Embery Way

**Comment by Jbcampbe** [comment]
^ @ekraihan could you clarify. I can make this change as a part of #144

**Comment by ekraihan** [comment]
that make more sense?

**Comment by Jbcampbe** [comment]
ah yes I gotcha. I will make sure to fix that.
