### ISSUE TITLE
Get 2 versions of the add page merged together

### ISSUE THREAD

**Issue by Jbcampbe** [Renascentinc/retina-app#153]

**Comment by Jbcampbe** [comment]
awhile back I created a `tool-form` component designed to take care of some tech debt. Never was implemented in prod

**Comment by ekraihan** [comment]
are you thinking to do this during this sprint?

**Comment by ekraihan** [comment]
I just wanted to make sure it wouldn't be a distraction

**Comment by Jbcampbe** [comment]
No not during this sprint. I was just looking through our backlog for retina app (seemed like we had a lot of issues open) and trying to get a feel for what is important and seeing if there is anything we can close
