### ISSUE TITLE
Inconsistency between names

### ISSUE THREAD

**Issue by ekraihan** [Renascentinc/retina-app#154]
On the add tool page, we have the field `Year of Manufacture` but on the tool info page, we have the field `Model Year` to represent the same field. This seems to be inconsistent. Maybe we should pick one or the other?

**Comment by amenders** [comment]
I like "model year"

Amos Endersen
(317) 600-9236

**Comment by Jbcampbe** [comment]
I don't want to be "that guy" (I feel like I am the one who usually asks this) but what do you think about moving this to a different release? It isn't really a bug so doesn't have to happen in a patch release

**Comment by ekraihan** [comment]
sure
