### ISSUE TITLE
Add Page

### ISSUE THREAD

**Issue by amenders** [Renascentinc/retina-app#21]
The add page needs several revisions, as per our 1.1.2017 meeting.

- [x] Re-order the entries for a more intuitive form

- [x] Add the serial number as a field

- [x] Add user data validation/standardization

- [x] Allow users to enter custom value in dropdowns if necessary

**Comment by ekraihan** [comment]
Thanks Mo. I think being able to track these issues will be helpful. Please let me know if i can help.

**Comment by amenders** [comment]
Does anyone know what order Josh was wanting these items it?

**Comment by Jbcampbe** [comment]
fix in PR #44
