### ISSUE TITLE
Tool page issues

### ISSUE THREAD

**Issue by amenders** [Renascentinc/retina-app#22]
The Tool page has several issues that need to be addressed

- [x] The `more >` button disappears on mouseover. Is this desired behavior?

- [x] The experience needs to be designed to allow users to click on any part of the tool `<div>` to add a tool to the cart.

- [x] Although this hasn't been a repeatable error, there have been occasions where the tool page loads with blank tools that have null values. Even though this is test data, we need to pin down why this happens.

- [x] The `transfer to` and `transfer` buttons need to have their properties redefined so that they sit centered in the menu section, and don't float up on the page.

- [x] I'm not sure it's an issue, but the transfer page is saying that the shop manager currently owns no tools, but I thought that as of our 1.4.2017 meeting, the transfer page was showing that he did have tools

**Comment by Jbcampbe** [comment]
@amenders did you find anything out about the third check mark here? I think other than that this issue is complete is that right?
