### ISSUE TITLE
Index page

### ISSUE THREAD

**Issue by amenders** [Renascentinc/retina-app#24]
We don't seem to have any need for an index page. Can we simply create a default page out of Add, Search, or Tool? We could always set up Index to be a bit of a splash page, but it seems that the Login page fulfills this purpose, and we can simply get rid of the Index page.

**Comment by Jbcampbe** [comment]
Yeah the app needed a place to land after the login page. Wasn't sure wether or not we want to direct the straight to any particular tab to start or if we wanted just a little filler splash thing and let them pick the tab they want to start with...

**Comment by Jbcampbe** [comment]
Per UX team lead decision the default page of the app is the `transfer` page. Any attempt to go to the `index` route will redirect to the `transfer` page
