### ISSUE TITLE
API calls

### ISSUE THREAD

**Issue by amenders** [Renascentinc/retina-app#25]
The following is a list of all the API calls the front end must make. Some have already been finished, but they are listed here so we can check off as we go.

- [x] `add page` Brand dropdown

- [x] `add page` Purchased From dropdown

- [x] `add page` Type dropdown

- [x] `add page` Add button

- [x] `search page` Status dropdown

- [x] `search page` Type dropdown

- [x] `search page` Owner dropdown

- [x] `search page` Brand dropdown

- [x] `search page` results population

- [x] `tool page` Status dropdown

- [x] `tool page` Type dropdown

- [x] `tool page` Brand dropdown

- [x] `tool page` results population

- [x] `tool page` Transfer To dropdown

- [x] `tool page` Transfer button

- [x] `info page` population

- [x] `login page` user check-in

- [x] `info page` change status

**Comment by Jbcampbe** [comment]
I believe we have implemented all api calls. Will reopen this issue if that changes
