### ISSUE TITLE
Reroute user to "https://etc..."

### ISSUE THREAD

**Issue by ekraihan** [Renascentinc/retina-app#36]
When I type "retina-app-develop.azurewebsites.net" into my browser, it takes me to "http://retina..." which is insecure and I can't log in. I have to actually type "https://retina...." to allow it to get me in. Would there be a way to automatically reroute the user to "https://..." ?

**Comment by Jbcampbe** [comment]
That used to be forced. I wonder if somehow in the git process we lost the changes😬

________________________________

**Comment by Jbcampbe** [comment]
This bug seems to have stopped happening. Will mark as closed for now. If it still seems like it is happening we can re-open
