### ISSUE TITLE
Transfer Page issues

### ISSUE THREAD

**Issue by ekraihan** [Renascentinc/retina-app#37]
- [x] When the shop manager views tools in the transfer page, he doesn't have the option to filter by _all_ owners

- [x] When I select a tool to transfer, navigate to another page, and then come back, the tool is still "selected" but it doesn't show up in my cart ( see video )
![cartissue](https://cloud.githubusercontent.com/assets/17623856/21701960/bbe9f76c-d376-11e6-907a-14fdee6012a3.gif)

**Comment by Jbcampbe** [comment]
Oooooh good catch. Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by Jbcampbe** [comment]
fixed with PR #45
