### ISSUE TITLE
Info Page Issues

### ISSUE THREAD

**Issue by ekraihan** [Renascentinc/retina-app#38]
- [x] The shop manager is not able to change the status of other's tools from the info page

- [x] Only allow user to change status or transfer tool from info page if they own the tool or they are the shop manager. A simple:

```
if (currentUser == ownerOfTool || current User == shopManager){
    display transfer and status change buttons
}
```
But in order to find out the id of the shop manager, we might need a new proc?

**Comment by ekraihan** [comment]
@amenders @JerebChase Any thoughts on this back and front end peeps?

**Comment by JerebChase** [comment]
This has been fixed on the backend.

**Comment by Jbcampbe** [comment]
finished front end side
