### ISSUE TITLE
People's Names Are Blank in Search and Transfer

### ISSUE THREAD

**Issue by ekraihan** [Renascentinc/retina-app#85]
This issue *was* resolved in Release 2.1.0, but it regressed. Not sure how or why.

**Comment by Jbcampbe** [comment]
@ekraihan didn't see this issue when I ran the latest `release_2.1.0` locally. were you sure you were on the latest release?

**Comment by ekraihan** [comment]
Hmmmm. Yea it works for me now that i made sure to be on the latest. OK!
Elias Kraihanzel
(317) 225-3413
ekraihan@umail.iu.edu

**Comment by Jbcampbe** [comment]
Marking as complete
