### ISSUE TITLE
Let "The Shop" filter by *any* owner on the transfer page

### ISSUE THREAD

**Issue by ekraihan** [Renascentinc/retina-app#86]
Currently, our logic says:
Given I am logged in as user "X" 
And I am on the transfer page
When I select the "owner" filter
Then I can only filter by "X" and "The Shop"

This means that when I log in as "The Shop" I can only filter by "The Shop" which isn't right, since "The Shop" can see *everybody's* tools on the transfer page and should therefore be able to filter by anyone's name.

**Comment by Jbcampbe** [comment]
@ekraihan I was a little confused about this use case. When would we want someone logging into the app as `The Shop`? I thought that since it is a location not a person we do not want anyone logging in as if they were a user.

**Comment by Jbcampbe** [comment]
We should probably focus on some other more important features but this does bring up a really good point. We should not be having locations as users that you can log in as. 

Created #87 to track this problem
