### ISSUE TITLE
Sometimes I Have to Log In Twice

### ISSUE THREAD

**Issue by ekraihan** [Renascentinc/retina-app#94]
Sometimes...
Given I am logged in as the "first" foreman
When I log out
And I log in as the "second" foreman
Then the login fails to complete
And I have to put in my credentials again

This is *not* happening in develop

![login_twice](https://cloud.githubusercontent.com/assets/17623856/26041553/c3ec4ef2-38fb-11e7-8859-ec6a1e8b718a.gif)

**Comment by Jbcampbe** [comment]
@ekraihan is there anything in the console when this happens?

**Comment by ekraihan** [comment]
Actually, the whole app practically refreshes. The console clears and then re-outputs the ember DEBUG info (see below)



Elias Kraihanzel
(317) 225-3413
ekraihan@umail.iu.edu

**Comment by Jbcampbe** [comment]
@amenders @ekraihan what do we think of either marking this as `wontfix` or pushing it off to a different release? Doesn't strike me as necessary for MVP

**Comment by amenders** [comment]
Agreed. Fine by me.

Amos Endersen
(317) 600-9236

**Comment by ekraihan** [comment]
Sure. :)

Elias Kraihanzel
(317) 225-3413
ekraihan@umail.iu.edu

**Comment by ekraihan** [comment]
@Jbcampbe @amenders I guess the *only* thing is that this wasn't happening before so *maybe* it wouldn't be too hard to fix? ;) But we can call it MVP for now

**Comment by ekraihan** [comment]
Closing this unless since it hasn't happened in a while
