### ISSUE TITLE
iPhone 5s/c UI issues

### ISSUE THREAD

**Issue by amenders** [Renascentinc/retina-app#96]
Several labels that cross the full width of the screen wrap to a second line on an iPhone 5s/c. We should fix these labels such that they can scale down to a screen of this size.

**Comment by ekraihan** [comment]
Dynamic CSS possibly?

**Comment by amenders** [comment]
That’d be entirely possible, but because of the intent of the situation, I would prefer a CSS solution that simply allowed for a larger range of screen sizes, since I think that should be doable.
